sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis

language: python

python:
  - "3.6"

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $BRANCH
  - ./build.sh prod deploy  
