sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis

language: python

python:
  - "3.6"

before-install:
  - cp containers/Dockerfile_prod .
  - docker build -t prod .
  - docker images

script:
  - python --version