sudo: required

services:
  - docker

branches:
  only:
    - master
    - release-candidate
    - travis

language: python

python:
  - "3.6.5"

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export IN_TRAVIS=1
  - ./build.sh prod deploy  
