sudo: required

services:
  - docker

branches:
  only:
    - master
    - release-candidate
    - travis

language: python

python:
  - "3.6.5"

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export IN_TRAVIS=1
  - ./build.sh prod deploy  

deploy:
  provider: heroku
  api_key: "pFalJ4vpllOK6ynsSsy9kDeky6l2LTuNiVjYp68ZOA4CB4drOBj+kyn+herkV1uYz+axn53XxqTqKQiy306LtHEnEL4wRwU/QStfSK5Y5TFdFVGOW6gKMITonpiaz5CNnLtA0VxMFxFw0uHW/fqK9uxL8T0r8A57YAo13aXGCBZQ0wSRsNhlqP8GvY1fvheoA+Ql2QF5jjecFJoq9iRZCuR2aeBI++U+6sfY6cD4Zyge+MOY2c6H4M9oXaWocDyXr+U38rxlpPxbuXa6At4cvUksuAQdXwSuXOc58Bf8WVLrJuLRlQFe+xphh9cgnNwsBz/kAbhmftvZr0oH14WmOQvK31VS1PD8KhVbleLBf5Tr5i16mIczU0vMVEFJyZuo+4t6mcYuSxYu7APG9AST8ISgq4NmIr+DrEDpYJ57dUUaJQ4eGbPH6wqgkAusnS7nYGdpoy95jo9Zi9/ExjbntFS/ED7h9hkRKxFYs1e9XIJJ0RtyokiFWHQsyVnzIYdojuLbM7KErNaiUTPQoDKjmbpLX3XW6+qYkbjuShUpJGgtQ99kLv+Hswob95vhi2UhMOu1kNamCJ6huhhCbfGqlYm4q7eAE1RO7aa/tlcSWfBE+V3s+/oM2JmncsQYViC24O95A6RO8F3dZ2Y7UjnZ5pIA5NyYrVIXYbsuhID3u9U="
  run: heroku container:release web --app itgetitest
