sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis

language: python

python:
  - "3.6"

script:
  - pwd
  - ls -la
  - ls app/app/static
  - python --version
  - cp containers/Dockerfile_dev ./Dockerfile
  - docker build -t devbuild .
  - docker images  
  - ./build.sh prod
  - ls app/app/static/dist
  - ./build.sh dev
  - ls app/app/static/dist

  
