sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis
    - release-candidate

language: python

python:
  - "3.6"

script:
  - export HEROKU_APP_NAME=itgeti
  - export HEROKU_DEV_APP_NAME=itgetidev
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - ./build.sh prod deploy  
