sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis

language: python

python:
  - "3.6"

script:
  - pwd
  - ls -la
  - python --version
  - cp containers/Dockerfile_prod .
  - docker build -t prod .
  - docker images

  
