sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis

language: python

python:
  - "3.6"

before_script:
  - cp containers/Dockerfile_dev ./Dockerfile
  - docker build -t devbuild .
  - docker images

script:
  - docker run -t -d -v $HOST_PATH/app:/opt/app/app --name devbuild devbuild 
  - docker exec devbuild 'npm' -c 'run' 'lint'
  - docker exec devbuild 'npm' -c 'run' 'flow'
  - docker exec devbuild 'npm' -c 'run' 'jest'
  - docker exec devbuild 'pytest'
  - docker exec devbuild 'flake8'
  - docker exec devbuild 'npm' -c 'run' 'webpack' '--' '--env.mode=prod'
  - docker stop devbuild
  - docker rm debbuild
  - cp containers/Dockerfile_prod ./Dockerfile
  - docker -build -t for_heroku .
  - docker images 

after_succes:
  - echo "successful test and build"
