FROM python:3.6.4-slim

WORKDIR /app

# This is the folder that will be shared with the docker host machine
# RUN mkdir shared

ADD requirements_prod.txt requirements.txt

RUN pip install -r requirements.txt

ADD shared/app/. .

ENV FLASK_APP my_app.py
# ENV FLASK_DEBUG 1

CMD ["bash"]

# CMD ["flask", "run", "--host=0.0.0.0"]
