FROM python:3.6.4-slim

WORKDIR /app

# This is the folder that will be shared with the docker host machine
# RUN mkdir shared

ADD requirements_prod.txt requirements.txt

RUN pip install --no-cache-dir -q -r requirements.txt

ADD shared/app/. .

# RUN adduser -D myuser
# USER myuser

# CMD echo $PORT

CMD gunicorn --bind 0.0.0.0:4000 wsgi 
