FROM node:9.8.0-stretch

WORKDIR /app

# This is the folder that will be shared with the docker host machine
RUN mkdir shared

ADD .eslintrc.json .
ADD .eslintignore .
ADD webpack.config.js .
ADD package.json .
ADD .babelrc .
ADD .flowconfig .

RUN npm install --save-dev eslint@4.18.2 \
													 eslint-plugin-import@2.9.0 \
													 eslint-config-airbnb-base@12.1.0 \
													 eslint-plugin-flowtype@2.46.1 \
													 webpack@4.1.1 \
													 webpack-cli@2.0.11 \
													 babel-preset-env@1.6.1 \
													 babel-loader@7.1.4 \
													 babel-core@6.26.0 \
													 babel-preset-flow@6.23.0 \
													 flow-bin@0.67.1 \
													 uglifyjs-webpack-plugin@1.2.3 \
													 babel-eslint@8.2.2
													 

# Update path so eslint can be run from anywhere
ENV PATH="/app/node_modules/.bin:${PATH}"

CMD ["bash"]

