FROM node:9.7.0-slim

WORKDIR /app

# This is the folder that will be shared with the docker host machine
RUN mkdir shared

ADD .eslintrc.json .
ADD .eslintignore .
ADD webpack.config.js .
ADD package.json .
ADD .babelrc .

RUN npm install --save-dev eslint eslint-plugin-import eslint-config-airbnb-base 
RUN npm install --save-dev webpack webpack-cli babel-preset-env babel-loader babel-core 


# Update path so eslint can be run from anywhere
ENV PATH="/app/node_modules/.bin:${PATH}"

CMD ["bash"]