# Development environment for:
#   - Python/JS Linting
#   - Python/JS Testing
#   - JS Building
#   - Flask debugging

FROM rschlub/nodepy:dev

# Linting
ADD .eslintrc.json .
ADD .eslintignore .
ADD .flowconfig .

# Packaging
ADD containers/dev/webpack.config.js .
ADD .babelrc .

# Python linting
ADD .flake8 .

# Environment variable for flask
ENV FLASK_APP app/my_app.py
ENV FLASK_DEBUG 1

# Use this is you want to load straight into flask
# CMD ["flask", "run", "--host=0.0.0.0"]

ENTRYPOINT ["bash"]